runtime: python39

env_variables:
  SECRET_KEY: "your-secret-key-change-this-in-production"
  
instance_class: F4

automatic_scaling:
  min_instances: 0
  max_instances: 20
  target_cpu_utilization: 0.7
  target_throughput_utilization: 0.7
  max_concurrent_requests: 50
  max_pending_latency: 15s

handlers:
- url: /static
  static_dir: static
  expiration: "1h"
  
- url: /.*
  script: main.app
  secure: always

# Increased timeout and workers for image generation
entrypoint: gunicorn -b :$PORT main:app --timeout 600 --workers 4 --threads 2 --worker-class sync

# Optional: VPC connector if you need it
# vpc_access_connector:
#   name: projects/YOUR_PROJECT/locations/YOUR_REGION/connectors/YOUR_CONNECTOR
